Make new submission notifications configurable
hackclub/hackathons-backend pull request #369
Opened 2023-12-23 19:49 UTC by northeastprince

2023-12-30 03:03 UTC, flexcommits approved these changes
LGTM!!!

2024-01-02 20:15 UTC, garyhtou requested changes
I like that we're doing this! There are a couple functional bugs to handle

2024-01-02 20:15 UTC, garyhtou commented on app/models/user/settings.rb
> +    scope :with_setting_not_disabled, ->(setting) { where("settings ->> ? IS NULL OR settings ->> ? != 'false'", setting.to_s, setting.to_s) }
The current code assumes `NULL` to be a falsy value. In reality, we likely want `NULL` to be the default value.

---

I think we might want:

```suggestion
    scope :with_setting_enabled, ->(setting) { where("COALESCE(settings ->> ?, ?) == 'true'", setting.to_s, User::DEFAULT_SETTINGS[setting]) }
```

or

```suggestion
    scope :with_setting, ->(setting, value) { where("COALESCE(settings ->> ?, ?) == ?", setting.to_s, User::DEFAULT_SETTINGS[setting], value) }
```

I haven't tested this code, but `COALESCE` should allow us to apply the default settings even if the database value is `NULL`.

---

side note: I wonder if `User::DEFAULT_SETTINGS[setting]` needs to be serialized as JSONB before being passed into the query above.

2024-01-02 20:15 UTC, garyhtou commented on app/views/hackathons/submission_mailer/admin_notification.html.erb
> +</p>
```suggestion
<% content_for :unsubscribe do %>
  <p>
    Don't wanna get these emails? <%= link_to "Toggle new submission notifications!", admin_submissions_notifications_url %>
  </p>
<% end %>
```

2024-01-02 20:15 UTC, garyhtou commented on app/views/hackathons/submission_mailer/admin_notification.text.erb
> +Toggle notifications for new submissions here: <%= admin_submissions_notifications_url %>
```suggestion
<% content_for :unsubscribe do %>
  Toggle notifications for new submissions here: <%= admin_submissions_notifications_url %>
<% end %>
```

2024-01-02 20:16 UTC, garyhtou commented
It might also be nice to add some tests around this

2024-01-02 20:22 UTC, garyhtou commented
Also, i just came across https://api.rubyonrails.org/classes/ActiveRecord/Store.html

might be handy!

2024-01-02 20:38 UTC, northeastprince commented
@garyhtou what would the benefit be vs jsonb?

2024-01-02 20:39 UTC, northeastprince commented
And yeah, I'm planning on adding tests once the implementation is sound.

2024-01-02 20:43 UTC, garyhtou commented
> @garyhtou what would the benefit be vs jsonb?

I haven't taken a close look into this. it seems like it supports

> dirty tracking methods (key_changed?, key_was and key_change)
https://api.rubyonrails.org/classes/ActiveRecord/Store.html#:~:text=dirty%20tracking%20methods%20(key_changed%3F%2C%20key_was%20and%20key_change)

but doesn't provide scopes. so it might not be the best fit for our needs. just wanted to share it in case you wanted to do a deep dive into it

2024-01-02 21:48 UTC, garyhtou approved these changes
the approach/design looks good to me!

2024-01-04 20:30 UTC, merged