Unsubscribe from Subscription via signed url
hackclub/hackathons-backend pull request #70
Opened 2023-07-26 06:16 UTC by garyhtou

Users can unsubscribe from a `Subscription` using a signed URL. This URL will be sent in `Digest` mailers. It's a simple `GET` to `/subscriptions/:id/unsubscribe`, where `:id` is a [signed id](https://api.rubyonrails.org/classes/ActiveRecord/SignedId.html) with an `unsubscribe` purpose.

Upon visiting an unsubscribe URL, you will see the following:
![image](https://github.com/hackclub/hackathons-backend/assets/20099646/b0408020-3279-46b7-8f9a-693b0916ba5e)

Unsubscribe URLs expire after 2 months.
![image](https://github.com/hackclub/hackathons-backend/assets/20099646/52347bd7-cde0-4031-b89d-f9f36903afd6)

If the signature in the signed id is invalid, the view will show it as an expired URL.

---

**Example URL:**
```
http://localhost:3000/subscriptions/eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik16QT0iLCJleHAiOiIyMDIzLTA5LTI2VDA1OjM3OjQ4LjQ5M1oiLCJwdXIiOiJoYWNrYXRob24vc3Vic2NyaXB0aW9uL3Vuc3Vic2NyaWJlIn19--b3e99639b45f15025099b3241ea287f2f921e3e26b1a168265f0c6578ca9c48b/unsubscribe
```

2023-07-26 12:37 UTC, northeastprince requested changes

2023-07-26 12:37 UTC, northeastprince commented on app/controllers/hackathon/subscriptions_controller.rb
> +  def unsubscribe
How about `edit` or in a `Subscriptions::RemovalsController`?

2023-07-26 12:46 UTC, northeastprince commented on test/controllers/hackathon/subscriptions_controller_test.rb
> +class Hackathon::SubscriptionsControllerTest < ActionDispatch::IntegrationTest
Maybe move this to a system test for consistency?

2023-07-26 12:46 UTC, northeastprince commented on test/controllers/hackathon/subscriptions_controller_test.rb
> +  test "should unsubscribe" do
```suggestion
  test "unsubscribing with a valid link" do
```

2023-07-26 12:46 UTC, northeastprince commented on test/controllers/hackathon/subscriptions_controller_test.rb
> +  test "should expire" do
```suggestion
  test "unsubscribing with an expired link" do
```

2023-07-26 12:46 UTC, northeastprince commented on test/controllers/hackathon/subscriptions_controller_test.rb
> +  test "should handle invalid signature" do
```suggestion
  test "unsubscribing with an invalid link" do
```

2023-07-26 12:46 UTC, northeastprince commented on app/models/hackathon/subscription/status.rb
> +  def unsubscribe_url
I don't think we should have a helper like this in the model.

2023-07-26 23:10 UTC, garyhtou commented
Since we ended up building out [`Digest`](https://github.com/hackclub/hackathons-backend/issues/39), each email will be contain **multiple** subscriptions. It's a little weird to have multiple unsubscribe links in an email. So I think this PR might be scrapped in favor of a "manage subscriptions" page.

The "manage subscriptions" will likely require some sort of ephemeral authentication provided via a signed unsubscribe url

2023-08-10 20:56 UTC, garyhtou commented
Closing in favor of https://github.com/hackclub/hackathons-backend/pull/85

2023-08-10 20:56 UTC, closed without merging